/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Bakery {
  export type SpiceStruct = {
    to: string;
    amount: BigNumberish;
    expiryTime: BigNumberish;
    salt: BigNumberish;
  };

  export type SpiceStructOutput = [string, BigNumber, BigNumber, BigNumber] & {
    to: string;
    amount: BigNumber;
    expiryTime: BigNumber;
    salt: BigNumber;
  };
}

export interface BakeryInterface extends utils.Interface {
  contractName: "Bakery";
  functions: {
    "MAX_NUMBER_OF_BLOCK_FOR_REWARD()": FunctionFragment;
    "MIN_WAIT_BETWEEN_BLOCK_FOR_REWARD()": FunctionFragment;
    "REWARD_PER_BLOCK()": FunctionFragment;
    "REWARD_PER_SPICE()": FunctionFragment;
    "bake(address,uint256)": FunctionFragment;
    "baker()": FunctionFragment;
    "bakerBoost(address,uint256[],uint256)": FunctionFragment;
    "bakerBoostMultiplier(uint256)": FunctionFragment;
    "bakerReward(address)": FunctionFragment;
    "cookie()": FunctionFragment;
    "earlyaccess()": FunctionFragment;
    "land()": FunctionFragment;
    "ovens(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "rebake((address,uint256,uint256,uint256),bytes)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "rewardPerSpice(address)": FunctionFragment;
    "salts(uint256)": FunctionFragment;
    "spice((address,uint256,uint256,uint256),bytes)": FunctionFragment;
    "spiceBoost(address)": FunctionFragment;
    "totalReward(address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unbake()": FunctionFragment;
    "upgrade()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MAX_NUMBER_OF_BLOCK_FOR_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_WAIT_BETWEEN_BLOCK_FOR_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_PER_BLOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_PER_SPICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bake",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "baker", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bakerBoost",
    values: [string, BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bakerBoostMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "bakerReward", values: [string]): string;
  encodeFunctionData(functionFragment: "cookie", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "earlyaccess",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "land", values?: undefined): string;
  encodeFunctionData(functionFragment: "ovens", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rebake",
    values: [Bakery.SpiceStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPerSpice",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "salts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "spice",
    values: [Bakery.SpiceStruct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "spiceBoost", values: [string]): string;
  encodeFunctionData(
    functionFragment: "totalReward",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "unbake", values?: undefined): string;
  encodeFunctionData(functionFragment: "upgrade", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_NUMBER_OF_BLOCK_FOR_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_WAIT_BETWEEN_BLOCK_FOR_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_PER_BLOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_PER_SPICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bakerBoost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bakerBoostMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bakerReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cookie", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "earlyaccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "land", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ovens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rebake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPerSpice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "salts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spiceBoost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unbake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Bakery extends BaseContract {
  contractName: "Bakery";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BakeryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_NUMBER_OF_BLOCK_FOR_REWARD(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    MIN_WAIT_BETWEEN_BLOCK_FOR_REWARD(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    REWARD_PER_BLOCK(overrides?: CallOverrides): Promise<[BigNumber]>;

    REWARD_PER_SPICE(overrides?: CallOverrides): Promise<[BigNumber]>;

    bake(
      token: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    baker(overrides?: CallOverrides): Promise<[string]>;

    bakerBoost(
      _to: string,
      _tokenBalances: BigNumberish[],
      nonZeroBalanceCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    bakerBoostMultiplier(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    bakerReward(
      _to: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[], BigNumber[]]>;

    cookie(overrides?: CallOverrides): Promise<[string]>;

    earlyaccess(overrides?: CallOverrides): Promise<[string]>;

    land(overrides?: CallOverrides): Promise<[string]>;

    ovens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        token: string;
        tokenId: BigNumber;
        startBlock: BigNumber;
        accumulatedSpiceAmount: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    rebake(
      _spice: Bakery.SpiceStruct,
      _signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rewardPerSpice(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    salts(arg0: BigNumberish, overrides?: CallOverrides): Promise<[boolean]>;

    spice(
      _spice: Bakery.SpiceStruct,
      _signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    spiceBoost(_to: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    totalReward(
      to: string,
      blockCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unbake(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgrade(overrides?: CallOverrides): Promise<[string]>;
  };

  MAX_NUMBER_OF_BLOCK_FOR_REWARD(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_WAIT_BETWEEN_BLOCK_FOR_REWARD(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  REWARD_PER_BLOCK(overrides?: CallOverrides): Promise<BigNumber>;

  REWARD_PER_SPICE(overrides?: CallOverrides): Promise<BigNumber>;

  bake(
    token: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  baker(overrides?: CallOverrides): Promise<string>;

  bakerBoost(
    _to: string,
    _tokenBalances: BigNumberish[],
    nonZeroBalanceCount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  bakerBoostMultiplier(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  bakerReward(
    _to: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber[], BigNumber[], BigNumber[]]>;

  cookie(overrides?: CallOverrides): Promise<string>;

  earlyaccess(overrides?: CallOverrides): Promise<string>;

  land(overrides?: CallOverrides): Promise<string>;

  ovens(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber] & {
      token: string;
      tokenId: BigNumber;
      startBlock: BigNumber;
      accumulatedSpiceAmount: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  rebake(
    _spice: Bakery.SpiceStruct,
    _signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rewardPerSpice(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  salts(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  spice(
    _spice: Bakery.SpiceStruct,
    _signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  spiceBoost(_to: string, overrides?: CallOverrides): Promise<BigNumber>;

  totalReward(
    to: string,
    blockCount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unbake(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgrade(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    MAX_NUMBER_OF_BLOCK_FOR_REWARD(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    MIN_WAIT_BETWEEN_BLOCK_FOR_REWARD(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    REWARD_PER_BLOCK(overrides?: CallOverrides): Promise<BigNumber>;

    REWARD_PER_SPICE(overrides?: CallOverrides): Promise<BigNumber>;

    bake(
      token: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    baker(overrides?: CallOverrides): Promise<string>;

    bakerBoost(
      _to: string,
      _tokenBalances: BigNumberish[],
      nonZeroBalanceCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    bakerBoostMultiplier(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bakerReward(
      _to: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[], BigNumber[]]>;

    cookie(overrides?: CallOverrides): Promise<string>;

    earlyaccess(overrides?: CallOverrides): Promise<string>;

    land(overrides?: CallOverrides): Promise<string>;

    ovens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        token: string;
        tokenId: BigNumber;
        startBlock: BigNumber;
        accumulatedSpiceAmount: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    rebake(
      _spice: Bakery.SpiceStruct,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    rewardPerSpice(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    salts(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    spice(
      _spice: Bakery.SpiceStruct,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    spiceBoost(_to: string, overrides?: CallOverrides): Promise<BigNumber>;

    totalReward(
      to: string,
      blockCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unbake(overrides?: CallOverrides): Promise<void>;

    upgrade(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    MAX_NUMBER_OF_BLOCK_FOR_REWARD(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    MIN_WAIT_BETWEEN_BLOCK_FOR_REWARD(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    REWARD_PER_BLOCK(overrides?: CallOverrides): Promise<BigNumber>;

    REWARD_PER_SPICE(overrides?: CallOverrides): Promise<BigNumber>;

    bake(
      token: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    baker(overrides?: CallOverrides): Promise<BigNumber>;

    bakerBoost(
      _to: string,
      _tokenBalances: BigNumberish[],
      nonZeroBalanceCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bakerBoostMultiplier(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bakerReward(_to: string, overrides?: CallOverrides): Promise<BigNumber>;

    cookie(overrides?: CallOverrides): Promise<BigNumber>;

    earlyaccess(overrides?: CallOverrides): Promise<BigNumber>;

    land(overrides?: CallOverrides): Promise<BigNumber>;

    ovens(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    rebake(
      _spice: Bakery.SpiceStruct,
      _signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rewardPerSpice(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    salts(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    spice(
      _spice: Bakery.SpiceStruct,
      _signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    spiceBoost(_to: string, overrides?: CallOverrides): Promise<BigNumber>;

    totalReward(
      to: string,
      blockCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unbake(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgrade(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_NUMBER_OF_BLOCK_FOR_REWARD(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MIN_WAIT_BETWEEN_BLOCK_FOR_REWARD(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    REWARD_PER_BLOCK(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REWARD_PER_SPICE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bake(
      token: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    baker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bakerBoost(
      _to: string,
      _tokenBalances: BigNumberish[],
      nonZeroBalanceCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bakerBoostMultiplier(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bakerReward(
      _to: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cookie(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    earlyaccess(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    land(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ovens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rebake(
      _spice: Bakery.SpiceStruct,
      _signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rewardPerSpice(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    salts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    spice(
      _spice: Bakery.SpiceStruct,
      _signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    spiceBoost(
      _to: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalReward(
      to: string,
      blockCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unbake(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgrade(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
