[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@ds-test/=lib/ds-test/src/', "@thirdweb/contracts/=lib/contracts/contracts/", "@openzeppelin/=lib/openzeppelin-contracts/"]
solc-version = '0.8.12'

# See more config options https://github.com/gakonst/foundry/tree/master/config
