[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  '@ds-test/=lib/ds-test/src/',
  "@thirdweb/contracts/=lib/contracts/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@prb-math/=lib/prb-math/"
]
solc-version = '0.8.12'
optimizer = true
optimizer_runs = 1000000

# See more config options https://github.com/gakonst/foundry/tree/master/config
